sudo: required
language: python

python:
  - "3.6"
services:
  - docker
env:
  global:
    - PYTHONUNBUFFERED=TRUE
    - CI_NODE_TOTAL=4
  jobs:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3

if: branch = master OR type = pull_request

install:
  - pip install pipsi
  - pipsi install .

script:
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      lambdipy release -v --parallel-index $CI_NODE_INDEX --parallel-total $CI_NODE_TOTAL
    else
      lambdipy release -v --dry-run --parallel-index $CI_NODE_INDEX --parallel-total $CI_NODE_TOTAL
    fi
